### PR TITLE
Modernize

### PR DESCRIPTION
**Pull request by jqr**
Brings the gem up to modern ruby gem standards.

Notable changes:
* Mentioned current generators in documentation
* Cleaned up human readable files, both content and formatting
* Use bundler gem building tasks
* Removed unused gems (capybara, factory_girl)

This branch can be easily viewed here for Markdown changes: https://github.com/expectedbehavior/active_mailer/tree/modernize

### CODE REVIEW

**Comment by jqr** [comment]
Would love a review @jason-o-matic / @esquivalient / @janxious.

**Comment by janxious** [comment]
There are some real lulz in there. This should probably be a new release version.

This looks really good, but I haven't tested the changes.

**Comment by jason-o-matic** [comment]
Ditto Joel.

**Comment by netshade** [comment]
Tests wouldn't run on 2.2.0 Ruby, added `test-unit` gem dependency to handle [removal of Test::Unit from Ruby stdlib](https://bugs.ruby-lang.org/issues/9711). Seems good to merge.

**Pull request merged**
