### PR TITLE
Rails 4.0 + 4.1 + 4.2 support

### PR DESCRIPTION
**Pull request by jqr**
This branch adds support for Rails 4.0 + 4.1 + 4.2.

Initially I started just porting straight to Rails 4.2, but then realized my app would need to do incremental upgrades from 3.2 through 4.0 and 4.1. So I looked around for a better solution to testing against multiple Rails versions and found the [Appraisal gem](https://github.com/thoughtbot/appraisal).

I then looked at some popular projects using Appraisal with similar constraints and used [Clearance](https://github.com/thoughtbot/clearance) for guidance, especially on how to have a minimal Rails app that was cross version compatible.

Once that was done it was obvious that all Rails 4.0+ versions were working so I went about re-adding 3.2 support which you can see in c0e5cbf.

### CODE REVIEW

**Comment by jason-o-matic** [comment]
:+1:

For fun I did this:
```
for i in `rbenv versions --bare`; do echo "TESTING ==== $i" && rbenv shell $i && ./script/setup && bundle exec rake; done
```
to test:
```
  1.9.3-p448
  1.9.3-p551
  2.1.3
  2.1.4
  2.1.5
  2.2.1
  2.2.2
  2.2.3
```
and they all passed.

**Comment by janxious** [comment]
It's weird this isn't mergeable?

**Comment by jqr** [comment]
@janxious Had one minor conflict, fixed :)

**Comment by janxious** [comment]
From a fresh rails 4.2.5 app + letter_opener + this branch + following the updated instructions I pushed up: 
screen shot 2015-12-13 at 10 55 42 pm


Anyway :+1:

**Comment by mediocretes** [comment]
Showing  4,435 changed files  with 164 additions and 9,453 deletions.

I did not realize that this gem was so vast?

**Comment by janxious** [comment]
It had a dummy rails app along with vendor'ed gems in it before.

**Comment by mediocretes** [comment]
Aha.

**Pull request merged**
